let mongoose = require("mongoose");

let InspectionSchema = mongoose.Schema({
    clientName: String,
    clientNumber:Number,
    vehicleMake: String,
    vehicleModel: String,
    vehicleVarient: String,
    vehicleYear: Number,
    vehicleTransmition: String,
    vehicleEngine: String,
    vehicleFuel: String,
    bodyColor: String,
    Milaege: String,
    registrationNumber: String,
    registrationCity: String,
    chasisNumber: String,
    enegineNumber: String,
    inspectionLocation: String,
    engineRoom: String,
    strutTower: String,
    leftStrutTower: String,
    rightFrontRail: String,
    leftFrontRail: String,
    radiatorCoreSupport: String,

    rightApillar: String,
    leftApillar: String,
    rightBpillar: String,
    leftBpillar: String,
    rightCpillar: String,
    leftCpillar: String,
    rightDpillar: String,
    leftDpillar: String,

    bootFloor: String,
    frontUnderbody: String,
    rearUnderbody: String,
    engineNoisy: String,
    engineVibration: String,
    engineSmoke: String,
    engineSmokeColor: String,
    engineBlow: String,
    coolantLeakage: String,
    brakeOilLeakage: String,
    transmissionOilLeakage: String,
    exhaustSound: String,
    radiator: String,
    suctionFan: String,
    gearTransmission: String,
    acInstalled: String,
    acFan: String,
    blowerThrow: String,
    acCooling: String,
    heater: String,
    SteeringWheelWearAndTear: String,
    SteeringWheelButtons: String,
    LightsLeverSwitch: String,
    Dashboard: String,
    DashControlButtons: String,
    InteriorLights: String,
    Defogger: String,
    Hazardlights: String,
    Multimedia: String,
    RearCamera: String,
    FrontViewCamera: String,
    FuelCapReleaseLever: String,
    FrontViewFuelCapReleaseLeverCamera: String,
    BonnetReleaseLever: String,
    SideviewMirrorAdjustment: String,
    LeftSideviewMirror: String,
    RightSideviewMirror: String,
    RetractingSideviewMirrors: String,
    ACGrills: String,
    AcceleratorPedal: String,
    BrakePedal: String,
    ClutchPedal: String,
    SeatsType: String,
    SeatsCondition: String,
    DriverSeatbelt: String,
    PassengerSeatbelt: String,
    WindowsType: String,
    FrontDriverWindow: String,
    FrontPassengerWindow: String,
    RearDriverSideWindow: String,
    RearPassengerSideWindow: String,
    WindowSafetyLockButton: String,
    CentralLocking: String,
    KeyButtons: String,
    FloorMats: String,
    FrontDriverDoorSeal: String,
    FrontPassengerDoorSeal: String,
    RearDriverSideDoorSeal: String,
    RearPassengerSideDoorSeal: String,
    BonnetSeal: String,
    TrunkSeal: String,
    Battery: String,
    Horn: String,
    RightHeadlightOperation: String,
    RightHeadlightCondition: String,
    RightHeadlight: String,
    LeftHeadlightOperation: String,
    LeftHeadlightCondition: String,
    LeftHeadlight: String,
    FoglightsOperation: String,
    LeftTailLightsOperation: String,
    LeftTailLightsCondition: String,
    LeftTailLights: String,
    RightTailLightsOperation: String,
    TrunkReleaseLever:String,
    RightTailLightsCondition: String,
    RightTailLights:String,
    WindshieldWipers:String,
    Airbags:String,
    CheckLights:String,
    FrontLeftShockAbsorber:String,
    FrontRightShockAbsorber:String,
    RearLeftShockAbsorber:String,
    RearRightShockAbsorber:String,
    LeftBush:String,
    RightBush:String,
    LeftBoot:String,
    RightBoot:String,
    TieRodEnd:String,
    LeftBallJoint:String,
    RightBallJoint:String,
    AxleBoots:String,
    SteeringAssemblyPlay:String,
    PassengerDPillar:String,
    PassengerCPillar:String,
    PassengerBPillar:String,
    PassengerAPillar:String,
    DriverDPillar:String,
    DriverCPillar:String,
    DriverBPillar:String,
    DriverAPillar:String,
    Pannels:String,
    Roof:String,
    FrontDriverDoor:String,
    RearDriverDoor:String,
    RearDriverFender:String,
    RearWindshield:String,
    Trunk:String,
    RearPassengerFender:String,
    RearPassengerDoor:String,
    FrontPassengerFender:String,
    FrontWindshield:String,
    Bonnet:String,
    FrontDriverFender:String,
    TrunkLock:String,
    FrontPassengerTyreBrand:String,
    FrontPassengerTyreSize:String,
    FrontPassengerTyreCondition:String,
    FrontDriverTyreBrand:String,
    FrontDriverTyreSize:String,
    FrontDriverTyreCondition:String,
    RearPassengerTyreBrand:String,
    RearPassengerTyreSize:String,
    RearPassengerTyreCondition:String,
    RearDriverTyreBrand:String,
    RearDriverTyreSize:String,
    RearDriverTyreCondition:String,
    AlloyRims:String,
    SpareWheel:String,
    ToolKit:String,
    Jack:String,
    PunctureRepairKit:String,
    TestDriveDoneBy:String,
    SpeedometerInformationCluster:String,
    SteeringWheelAlignment:String,
    SteeringFunction:String,
    RearSuspensionNoise:String,
    FrontSuspensionNoise:String,
    BrakePedalOperation:String,
    ABSActuation:String,
    DriveShaftNoise:String,
    DifferentialNoise:String,
    GearShifting:String,
    EnginePick:String,
    inspectorName:String,
    inspectorEmail:String,
    inspectorNumber:Number,
    inspectorLocation:String,
    
    date: {
        type: Date,
        default: Date.now,
    },
})

let Inspection = mongoose.model('Inspection', InspectionSchema);

module.exports = Inspection;